spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_vendor
    username: postgres
    password: 3011
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view:
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true


#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
#  main:
#    web-application-type: servlet

